language: node_js
node_js:
  - "stable"
before_script:
  - export TZ=Europe/Madrid
script: npm run travis
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
cache:
  yarn: true
  directories:
    - ~/.yarn
    - ~/.nvm
